language: elixir
sudo: false
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.4
otp_release:
  - 18.3
  - 19.3
  - 20.3
matrix:
  exclude:
    - elixir: 1.4.5
      otp_release: 18.3
    - elixir: 1.6.4
      otp_release: 18.3
    - elixir: 1.3.4
      otp_release: 20.3
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "mix do deps.get, deps.compile, compile --warnings-as-errors, dialyzer --halt-exit-status, coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
